### PR TITLE
add a separate overload-group calculation in the unified graph collector

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Bug/issue #, if applicable: rdar://131639487

## Summary

This PR updates the unified symbol graph collector to optionally create overload groups separately from the previous iteration, where it combined pre-existing overload groups created on individual symbol graphs. To preserve API compatibility (and use outside of unified symbol graphs), the other mechanisms are preserved, but they suffer from a bug. When overloads are added in disjoint sets, whether from an extension or from alternate platforms, the old overload grouping code failed to combine them together. This updated code ensures that all overload groups reflect all of the available symbols, regardless of their source.

## Dependencies

None

## Testing

A companion PR on Swift-DocC will go more in-depth into testing. This PR contains additional automated tests that demonstrate the new behavior.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
I chatted with @daniel-grumberg and @mayaepps about this PR offline. We found a couple things to change:

1. Make sure that protocol implementations are still not grouped with their original requirement.
2. Parameterize the existing tests to make sure they all work with the new code.

I'll work on these points later today.

**Comment by mayaepps** [comment]
A small late-breaking thought 😄

> To preserve API compatibility (and use outside of unified symbol graphs), the other mechanisms are preserved, but they suffer from a bug.

The old code will still suffer from this bug after this change, right? Is that something we should note somewhere so it's not forgotten?

**Comment by QuietMisdreavus** [comment]
@mayaepps That's definitely worth noting! I've wanted to write up a doc article about the overloads implementation at some point. I think in the meantime i can throw a warning into a doc comment.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by daniel-grumberg — APPROVED** [review]
LGTM!

**Pull request merged**
